import { Inter } from 'next/font/google';
import { dir } from 'i18next';
import StyledComponentsRegistry from '../lib/registry';
import { languages } from '../i18n/settings';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <div className="App">{children}</div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
