import { Inter } from 'next/font/google';
import { dir } from 'i18next';
import StyledComponentsRegistry from '../lib/registry';
import { languages } from '../i18n/settings';
import { ReduxProvider } from '../store/Provider';
import './globals.css';
import { Provider } from 'react-redux';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ReduxProvider>
            <div className="App">{children}</div>
          </ReduxProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

export default RootLayout;
